apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flask-hello-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-hello
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "6001"
        prometheus.io/path: ""
    spec:
      containers:
      - name: api
        image: IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 6000
        - containerPort: 6001
      imagePullSecrets:
       - name: k8spoc-registry
---
kind: Service
apiVersion: v1
metadata:
  name: flask-hello-service
spec:
  type: NodePort
  selector:
    app: flask-hello
  ports:
    - protocol: TCP
      port: 6000
